spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_survey?useUnicode=true&characterEncoding=utf8
    username: root
    password: se434

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/scau/mapper/xml/*.xml

server:
  port: 80
